services:
  postgres_auth:
    image: postgres:16
    container_name: contenedor_postgres_auth
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ms_auth
    ports:
      - "5433:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data

  ms_auth:
    build:
      context: .
      dockerfile: backend/ms_auth/Dockerfile
    container_name: microservicio_auth
    restart: always
    environment:
      NODE_ENV: development

      REST_PORT: 3001
      GRPC_PORT: 50051

      DB_HOST: postgres_auth
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: ms_auth

      JWT_SECRET: super_secret_cambialo_despues
      JWT_EXPIRES_IN: 1h

      JWT_REFRESH_SECRET: super_refresh_secret_cambialo_despues
      JWT_REFRESH_EXPIRES_IN: 7d

      PASSWORD_RESET_EXPIRES_MINUTES: 15

      PROTO_AUTH_PATH: /app/proto/auth.proto
    ports:
      - "3001:3001"
      - "50051:50051"
    depends_on:
      - postgres_auth    

  postgres_periodos:
    image: postgres:16
    container_name: contenedor_postgres_periodos
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ms_periodos
    ports:
      - "5434:5432"
    volumes:
      - postgres_periodos_data:/var/lib/postgresql/data

  ms_periodos:
    build:
      context: .
      dockerfile: backend/ms_periodos/Dockerfile
    container_name: microservicio_periodos
    restart: always
    environment:
      NODE_ENV: development
      DB_HOST: postgres_periodos
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: ms_periodos
    ports:
      - "3002:3002"
    depends_on:
      - postgres_periodos

  postgres_docentes_alumnos:
    image: postgres:16
    container_name: contenedor_postgres_docentes_alumnos
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ms_docentes_alumnos
    ports:
      - "5435:5432"
    volumes:
    - postgres_docentes_alumnos_data:/var/lib/postgresql/data
  
  ms_docentes_alumnos:
    build:
      context: .
      dockerfile: backend/ms_docentes_alumnos/Dockerfile
    container_name: microservicio_docentes_alumnos
    restart: always
    environment:
      NODE_ENV: development
      DB_HOST: postgres_docentes_alumnos
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: ms_docentes_alumnos
    ports:
      - "3003:3003"
      - "50053:50053"
    depends_on:
      - postgres_docentes_alumnos


  postgres_notificaciones:
    image: postgres:16
    container_name: contenedor_postgres_notificaciones
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ms_notificaciones
    ports:
      - "5436:5432"
    volumes:
      - postgres_notificaciones_data:/var/lib/postgresql/data   
      
  ms_notificaciones:
    build:
      context: .
      dockerfile: backend/ms_notificaciones/Dockerfile
    container_name: microservicio_notificaciones
    restart: always
    environment:
      NODE_ENV: development

      REST_PORT: 3006
      GRPC_PORT: 50056

      DB_HOST: postgres_notificaciones
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: ms_notificaciones

      SMTP_HOST: smtp.mailtrap.io
      SMTP_PORT: 2525
      SMTP_USER: change_me
      SMTP_PASS: change_me
      SMTP_FROM: "AGM System <no-reply@agm.com>"

      PROTO_NOTIFICACIONES_PATH: /app/proto/notificaciones.proto
    ports:
      - "3006:3006"
      - "50056:50056"
    depends_on:
      - postgres_notificaciones       


  api_gateway:
    build:
      context: .
      dockerfile: backend/api_gateway/Dockerfile
    container_name: microservicio_api_gateway
    restart: always
    environment:
      NODE_ENV: development
      PORT: 3000
      MS_AUTH_URL: http://ms_auth:3001
      MS_NOTIFICACIONES_URL: http://ms_notificaciones:3006
    ports:
      - "3000:3000"
    depends_on:
      - ms_auth
      - ms_notificaciones    

  redis:
    image: redis:7

    container_name: redis_asistencias
    
    ports:
      - "6379:6379"

  postgres_asistencias:
    image: postgres:16
    container_name:
      contenedor_postgres_asistencias
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ms_asistencias
    ports:
      - "5437:5432"
    volumes:
      - postgres_asistencias_data:/var/lib/postgresql/data

  ms_asistencias:
    build:
      context: .
      dockerfile:
        backend/ms_asistencias/Dockerfile
    container_name:
      microservicio_asistencias
    restart: always
    environment:
      NODE_ENV: development
      PORT: 3005
      DB_HOST: postgres_asistencias
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: ms_asistencias
      JWT_SECRET: super_secret_qr_key
      REDIS_HOST: redis
      REDIS_PORT: 6379
      GRPC_PORT: 50055
    ports:
      - "3005:3005"
      - "50055:50055"
    depends_on:
      - postgres_asistencias
      - redis

volumes:
  postgres_auth_data:
  postgres_periodos_data:
  postgres_notificaciones_data:
  postgres_docentes_alumnos_data:
  postgres_asistencias_data: